using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using RefractorForge.Formats.Geometry;

namespace RefractorForge.Formats.Con;

/// <summary>
/// Writes the gameplay layer back to Refractor <c>.con</c> files. The three instance files
/// (ControlPoints / ObjectSpawns / SoldierSpawns) are regenerated from the edited model; capture
/// radii — which live on the control-point <em>templates</em> — are patched surgically into
/// ControlPointTemplates.con so every unrelated template property is preserved verbatim.
/// </summary>
public static class GameplayWriter
{
    private const string NL = "\r\n";   // Refractor .con files use CRLF
    private static string F(float v) => v.ToString("0.######", CultureInfo.InvariantCulture);
    private static string Pos(Vec3 v) => $"{F(v.X)}/{F(v.Y)}/{F(v.Z)}";

    public static string BuildControlPoints(IReadOnlyList<ControlPointDef> cps)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var c in cps)
        {
            sb.Append("Object.create ").Append(c.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(c.Position)).Append(NL);
            // Only when the flag actually carries one, so a level that never had the line does not gain it.
            if (c.Rotation.X != 0f || c.Rotation.Y != 0f || c.Rotation.Z != 0f)
                sb.Append("Object.rotation ").Append(Pos(c.Rotation)).Append(NL);
            sb.Append(NL);
        }
        return sb.ToString();
    }

    public static string BuildObjectSpawns(IReadOnlyList<VehicleSpawnDef> spawns)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var s in spawns)
        {
            sb.Append("Object.create ").Append(s.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(s.Position)).Append(NL)
              .Append("Object.rotation ").Append(Pos(s.Rotation)).Append(NL)
              .Append("Object.setTeam ").Append(s.Team.ToString(CultureInfo.InvariantCulture)).Append(NL);
            if (s.OsId != 0)   // only emit setOSId when the spawn is actually linked to a CP's objectSpawnerId (0 = unlinked, nearest-CP)
                sb.Append("Object.setOSId ").Append(s.OsId.ToString(CultureInfo.InvariantCulture)).Append(NL);
            sb.Append(NL);
        }
        return sb.ToString();
    }

    public static string BuildSoldierSpawns(IReadOnlyList<SoldierSpawnDef> spawns)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var s in spawns)
            sb.Append("Object.create ").Append(s.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(s.Position)).Append(NL)
              .Append("Object.rotation ").Append(Pos(s.Rotation)).Append(NL).Append(NL);
        return sb.ToString();
    }

    /// <summary>Write the three instance files into <paramref name="dir"/>.</summary>
    public static void WriteInstanceFiles(string dir, GameplayObjects gp)
    {
        File.WriteAllText(Path.Combine(dir, "ControlPoints.con"), BuildControlPoints(gp.ControlPoints));
        File.WriteAllText(Path.Combine(dir, "ObjectSpawns.con"), BuildObjectSpawns(gp.VehicleSpawns));
        File.WriteAllText(Path.Combine(dir, "SoldierSpawns.con"), BuildSoldierSpawns(gp.SoldierSpawns));
    }

    /// <summary>Surgically rewrite the editable control-point template properties (radius, team, areaValue,
    /// conversionTime, controlPointName) for each template whose name matches an edited control point. Only
    /// EXISTING lines are rewritten; every other line is preserved exactly. Returns the patched text.</summary>
    public static string PatchControlPointRadii(IEnumerable<string> templateLines, IReadOnlyList<ControlPointDef> cps)
    {
        var byName = new Dictionary<string, ControlPointDef>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var c in cps) byName[c.Name] = c;   // last write wins

        var sb = new StringBuilder();
        ControlPointDef? cur = null;
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";

            if (key == "objecttemplate.create")
            {
                string? name = sp.Length >= 3 ? sp[2] : (sp.Length >= 2 ? sp[1] : null);   // "create ControlPoint <name>"
                cur = name is not null && byName.TryGetValue(name, out var c) ? c : null;
            }
            else if (cur is ControlPointDef cp)
            {
                string? repl = key switch
                {
                    "objecttemplate.radius" => "ObjectTemplate.radius " + cp.Radius.ToString("0.###", CultureInfo.InvariantCulture),
                    "objecttemplate.team" => "ObjectTemplate.team " + cp.Team.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.areavalue" => "ObjectTemplate.areaValue " + cp.AreaValue.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.conversiontime" => "ObjectTemplate.conversionTime " + cp.ConversionTime.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.controlpointname" when !string.IsNullOrEmpty(cp.ControlPointName) => "ObjectTemplate.controlPointName " + cp.ControlPointName,
                    // BF1942 control-point timing / behaviour fields (Battlecraft "Edit Control Point" dialog).
                    "objecttemplate.timetogetcontrol" => "ObjectTemplate.timeToGetControl " + cp.TimeToGetControl.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.timetolosecontrol" => "ObjectTemplate.timeToLoseControl " + cp.TimeToLoseControl.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.disableifenemyinsideradius" => "ObjectTemplate.disableIfEnemyInsideRadius " + cp.DisableIfEnemyInside.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.disablewhenlosingcontrol" => "ObjectTemplate.disableWhenLosingControl " + cp.DisableWhenLosing.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.losecontrolwhenenemyclose" => "ObjectTemplate.loseControlWhenEnemyClose " + cp.LoseControlWhenEnemyClose.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.losecontrolwhennotclose" => "ObjectTemplate.loseControlWhenNotClose " + cp.LoseControlWhenNotClose.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.unabletochangeteam" => "ObjectTemplate.unableToChangeTeam " + cp.UnableToChangeTeam.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.onlytakablebyteam" => "ObjectTemplate.onlyTakableByTeam " + cp.OnlyTakableByTeam.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.hascollisionphysics" => "ObjectTemplate.hasCollisionPhysics " + cp.HasCollisionPhysics.ToString(CultureInfo.InvariantCulture),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    sb.Append(line, 0, indent).Append(repl).Append(NL);
                    continue;
                }
            }
            sb.Append(line).Append(NL);
        }
        return sb.ToString();
    }

    public static void PatchControlPointRadiiFile(string templateConPath, IReadOnlyList<ControlPointDef> cps)
    {
        if (!File.Exists(templateConPath)) return;
        var patched = PatchControlPointRadii(File.ReadAllLines(templateConPath), cps);
        File.WriteAllText(templateConPath, patched);
    }

    /// <summary>
    /// Surgically move/re-aim the instances in an EXISTING gameplay instance file, matching by the name on
    /// <c>Object.create</c>. Only <c>absolutePosition</c> / <c>rotation</c> / <c>setTeam</c> / <c>setOSId</c> lines
    /// of matched objects are rewritten; every other line - comments, ordering, and any instance this edit does
    /// not know about - is preserved exactly.
    ///
    /// This is how an edit reaches a level's OTHER game modes. A map ships parallel <c>Conquest/</c>, <c>Ctf/</c>,
    /// <c>TDM/</c> and <c>SinglePlayer/</c> folders that share most objects but deliberately differ (Kharkov_Day2
    /// ships 5 control points for Conquest and TDM but only 3 for CTF), and the shared ones sit at identical
    /// coordinates. So moving a flag must move it in every mode that HAS that flag, while never adding a
    /// Conquest-only object to CTF or deleting a CTF-only one - which is exactly what rewriting the file wholesale
    /// would do.
    /// </summary>
    /// <summary>
    /// Carry the edits made in ONE game mode across to the map's other modes, by moving only what actually moved.
    ///
    /// <paramref name="original"/> is the mode the editor loaded, as it was on disk; <paramref name="gp"/> is that
    /// same list after editing, so pairing them by index yields the real before/after of every instance. An
    /// instance in another mode is rewritten only when it sits where an edited one used to, which makes it the
    /// same placement. Everything else is left byte-for-byte alone.
    ///
    /// The alternative - matching by template name or by ordinal - cannot tell instances apart. Bocage declares
    /// eight AAGunSpawner in one file, so name-keying collapsed all eight onto the last one's position, and
    /// ordinal-keying stamped Conquest's layout over SinglePlayer's whenever the two happened to hold the same
    /// number of spawners. Both corrupted maps on a save with no edits at all.
    /// </summary>
    public static string PatchInstanceTransforms(IEnumerable<string> lines, GameplayObjects original, GameplayObjects gp)
    {
        // old position -> what that instance looks like now, for the ones that changed.
        var moved = new List<(string Name, Vec3 From, Vec3 Pos, Vec3? Rot, int? Team, int? OsId)>();
        void Pair(string n, Vec3 from, Vec3 to, Vec3? rot, int? team, int? osId, bool changed)
        { if (changed) moved.Add((n, from, to, rot, team, osId)); }

        for (int i = 0; i < System.Math.Min(original.ControlPoints.Count, gp.ControlPoints.Count); i++)
        {
            var (o, n) = (original.ControlPoints[i], gp.ControlPoints[i]);
            if (!o.Name.Equals(n.Name, System.StringComparison.OrdinalIgnoreCase)) continue;
            Pair(n.Name, o.Position, n.Position, null, null, null, !Same(o.Position, n.Position));
        }
        for (int i = 0; i < System.Math.Min(original.SoldierSpawns.Count, gp.SoldierSpawns.Count); i++)
        {
            var (o, n) = (original.SoldierSpawns[i], gp.SoldierSpawns[i]);
            if (!o.Name.Equals(n.Name, System.StringComparison.OrdinalIgnoreCase)) continue;
            Pair(n.Name, o.Position, n.Position, n.Rotation, null, null, !Same(o.Position, n.Position) || !Same(o.Rotation, n.Rotation));
        }
        for (int i = 0; i < System.Math.Min(original.VehicleSpawns.Count, gp.VehicleSpawns.Count); i++)
        {
            var (o, n) = (original.VehicleSpawns[i], gp.VehicleSpawns[i]);
            if (!o.Name.Equals(n.Name, System.StringComparison.OrdinalIgnoreCase)) continue;
            Pair(n.Name, o.Position, n.Position, n.Rotation, n.Team, n.OsId != 0 ? n.OsId : null,
                 !Same(o.Position, n.Position) || !Same(o.Rotation, n.Rotation) || o.Team != n.Team || o.OsId != n.OsId);
        }

        if (moved.Count == 0) return string.Join(NL, lines.Select(l => l.Replace("\r", "").Replace("\n", ""))) + NL;

        var sb = new StringBuilder();
        (Vec3 Pos, Vec3? Rot, int? Team, int? OsId)? cur = null;
        var pending = new List<string>();
        string? curName = null;

        // A block's identity is its position, which only appears AFTER Object.create - so buffer each block and
        // resolve it once its position is known.
        void FlushBlock()
        {
            foreach (var l in pending) sb.Append(l).Append(NL);
            pending.Clear(); cur = null; curName = null;
        }

        var all = lines.Select(l => l.Replace("\r", "").Replace("\n", "")).ToList();
        for (int i = 0; i < all.Count; i++)
        {
            var line = all[i];
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";

            if (key == "object.create")
            {
                FlushBlock();
                curName = sp.Length >= 2 ? sp[1] : null;
                pending.Add(line);
                continue;
            }
            if (curName is null) { sb.Append(line).Append(NL); continue; }

            if (key == "object.absoluteposition" && cur is null && sp.Length >= 2 && TryVec(sp[1], out var here))
            {
                // Same template sitting where an edited instance used to be: this is that instance.
                foreach (var m in moved)
                    if (m.Name.Equals(curName, System.StringComparison.OrdinalIgnoreCase) && Same(m.From, here))
                    { cur = (m.Pos, m.Rot, m.Team, m.OsId); break; }
            }

            if (cur is not null)
            {
                var v = cur.Value;
                string? repl = key switch
                {
                    "object.absoluteposition" => "Object.absolutePosition " + Pos(v.Pos),
                    "object.rotation" when v.Rot is not null => "Object.rotation " + Pos(v.Rot.Value),
                    "object.setteam" when v.Team is not null => "Object.setTeam " + v.Team.Value.ToString(CultureInfo.InvariantCulture),
                    "object.setosid" when v.OsId is not null => "Object.setOSId " + v.OsId.Value.ToString(CultureInfo.InvariantCulture),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    pending.Add(line[..indent] + repl);
                    continue;
                }
            }
            pending.Add(line);
        }
        FlushBlock();
        return sb.ToString();
    }

    private static bool Same(Vec3 a, Vec3 b)
        => System.MathF.Abs(a.X - b.X) < 0.005f && System.MathF.Abs(a.Y - b.Y) < 0.005f && System.MathF.Abs(a.Z - b.Z) < 0.005f;

    private static bool TryVec(string s, out Vec3 v)
    {
        v = Vec3.Zero;
        var p = s.Split('/');
        if (p.Length < 3) return false;
        if (float.TryParse(p[0], NumberStyles.Float, CultureInfo.InvariantCulture, out var x)
            && float.TryParse(p[1], NumberStyles.Float, CultureInfo.InvariantCulture, out var y)
            && float.TryParse(p[2], NumberStyles.Float, CultureInfo.InvariantCulture, out var z))
        { v = new Vec3(x, y, z); return true; }
        return false;
    }

    /// <summary>Older two-argument form: with no "before" to compare against nothing can be identified as moved,
    /// so the file is returned unchanged rather than guessed at.</summary>
    public static string PatchInstanceTransforms(IEnumerable<string> lines, GameplayObjects gp)
        => PatchInstanceTransforms(lines, gp, gp);


    /// <summary>Apply <see cref="PatchInstanceTransforms"/> to whichever of the three instance files exist in
    /// <paramref name="dir"/>. Returns the paths actually rewritten.</summary>
    public static List<string> PatchInstanceFiles(string dir, GameplayObjects original, GameplayObjects gp)
    {
        var touched = new List<string>();
        foreach (var name in new[] { "ControlPoints.con", "ObjectSpawns.con", "SoldierSpawns.con" })
        {
            var p = Path.Combine(dir, name);
            if (!File.Exists(p)) continue;
            File.WriteAllText(p, PatchInstanceTransforms(File.ReadAllLines(p), original, gp));
            touched.Add(p);
        }
        return touched;
    }

    /// <summary>Append <c>ObjectSpawner</c> templates for vehicle spawns that don't already have one (i.e.
    /// newly placed spawners), linking each to its chosen vehicle for both teams so it spawns in-game.
    /// Existing templates are preserved verbatim; spawns with no vehicle set or a known name are skipped.</summary>
    public static string AppendMissingSpawnerTemplates(IEnumerable<string> templateLines, IReadOnlyList<VehicleSpawnDef> spawns)
    {
        var have = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        var sb = new StringBuilder();
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var t = line.TrimStart();
            if (t.ToLowerInvariant().StartsWith("objecttemplate.create") && t.ToLowerInvariant().Contains("objectspawner"))
            {
                var sp = t.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
                if (sp.Length >= 3) have.Add(sp[2]);
            }
            sb.Append(line).Append(NL);
        }

        var added = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var s in spawns)
        {
            if (string.IsNullOrWhiteSpace(s.Vehicle) || have.Contains(s.Name) || !added.Add(s.Name)) continue;
            sb.Append(NL).Append("rem  Added by RefractorForge").Append(NL)
              .Append("ObjectTemplate.create ObjectSpawner ").Append(s.Name).Append(NL)
              .Append("ObjectTemplate.setObjectTemplate 1 ").Append(s.Vehicle).Append(NL)
              .Append("ObjectTemplate.setObjectTemplate 2 ").Append(s.Vehicle).Append(NL)
              .Append("ObjectTemplate.SpawnDelay 20").Append(NL)
              .Append("ObjectTemplate.SpawnDelayAtStart 0").Append(NL)
              .Append("ObjectTemplate.TimeToLive 120").Append(NL)
              .Append("ObjectTemplate.Distance 200").Append(NL);
        }
        return sb.ToString();
    }

    /// <summary>Rewrite the editable ObjectSpawner template fields Battlecraft exposes (guide figure 24): the two
    /// per-team vehicles and the spawn timing. Only lines that ALREADY EXIST are rewritten - a template that never
    /// declared, say, DamageWhenLost keeps its silence rather than gaining a value the level never had. Everything
    /// else is preserved verbatim, exactly like PatchSoldierSpawnTemplates.</summary>
    public static string PatchVehicleSpawnTemplates(IEnumerable<string> templateLines, IReadOnlyList<VehicleSpawnDef> spawns)
    {
        var byName = new Dictionary<string, VehicleSpawnDef>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var s in spawns) byName[s.Name] = s;
        var sb = new StringBuilder();
        VehicleSpawnDef? cur = null;
        foreach (var raw in templateLines)
        {
            var line = raw.Replace(((char)13).ToString(), "").Replace(((char)10).ToString(), "");
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', (char)9 }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";
            if (key == "objecttemplate.create")
            {
                string? name = sp.Length >= 3 ? sp[2] : (sp.Length >= 2 ? sp[1] : null);   // "create ObjectSpawner <name>"
                cur = name is not null && byName.TryGetValue(name, out var v) ? v : null;
            }
            else if (cur is VehicleSpawnDef vs)
            {
                string N(int v) => v.ToString(CultureInfo.InvariantCulture);
                string? repl = key switch
                {
                    "objecttemplate.setobjecttemplate" when sp.Length >= 3 && sp[1] == "1" && vs.Vehicle1.Length > 0
                        => "ObjectTemplate.setObjectTemplate 1 " + vs.Vehicle1,
                    "objecttemplate.setobjecttemplate" when sp.Length >= 3 && sp[1] == "2" && vs.Vehicle2.Length > 0
                        => "ObjectTemplate.setObjectTemplate 2 " + vs.Vehicle2,
                    "objecttemplate.minspawndelay" => "ObjectTemplate.MinSpawnDelay " + N(vs.MinSpawnDelay),
                    "objecttemplate.maxspawndelay" => "ObjectTemplate.MaxSpawnDelay " + N(vs.MaxSpawnDelay),
                    // A level with the single SpawnDelay form keeps that form; min is what the editor shows for it.
                    "objecttemplate.spawndelay" => "ObjectTemplate.SpawnDelay " + N(vs.MinSpawnDelay),
                    "objecttemplate.spawndelayatstart" => "ObjectTemplate.SpawnDelayAtStart " + N(vs.SpawnDelayAtStart),
                    "objecttemplate.timetolive" => "ObjectTemplate.TimeToLive " + N(vs.TimeToLive),
                    "objecttemplate.distance" => "ObjectTemplate.Distance " + N(vs.Distance),
                    "objecttemplate.damagewhenlost" => "ObjectTemplate.DamageWhenLost " + N(vs.DamageWhenLost),
                    "objecttemplate.maxnrofobjectspawned" => "ObjectTemplate.MaxNrOfObjectSpawned " + N(vs.MaxNrOfObjectSpawned),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    sb.Append(line, 0, indent).Append(repl).Append(NL);
                    continue;
                }
            }
            sb.Append(line).Append(NL);
        }
        return sb.ToString();
    }

    /// <summary>Surgically rewrite the editable soldier-spawn template fields (setGroup / setSpawnId /
    /// spawnAsParaTrooper) for each SpawnPoint template whose name matches an edited soldier spawn. Only EXISTING
    /// lines are rewritten; every other line is preserved verbatim (mirrors <see cref="PatchControlPointRadii"/>).</summary>
    public static string PatchSoldierSpawnTemplates(IEnumerable<string> templateLines, IReadOnlyList<SoldierSpawnDef> spawns)
    {
        var byName = new Dictionary<string, SoldierSpawnDef>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var s in spawns) byName[s.Name] = s;
        var sb = new StringBuilder();
        SoldierSpawnDef? cur = null;
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";
            if (key == "objecttemplate.create")
            {
                string? name = sp.Length >= 3 ? sp[2] : (sp.Length >= 2 ? sp[1] : null);   // "create SpawnPoint <name>"
                cur = name is not null && byName.TryGetValue(name, out var s) ? s : null;
            }
            else if (cur is SoldierSpawnDef ss)
            {
                string? repl = key switch
                {
                    "objecttemplate.setgroup" => "ObjectTemplate.setGroup " + ss.Group.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.setspawnid" => "ObjectTemplate.setSpawnId " + ss.SpawnId.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.spawnasparatrooper" => "ObjectTemplate.spawnAsParaTrooper " + ss.SpawnAsParaTrooper.ToString(CultureInfo.InvariantCulture),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    sb.Append(line, 0, indent).Append(repl).Append(NL);
                    continue;
                }
            }
            sb.Append(line).Append(NL);
        }
        return sb.ToString();
    }

    public static void PatchSoldierSpawnTemplatesFile(string templateConPath, IReadOnlyList<SoldierSpawnDef> spawns)
    {
        if (!File.Exists(templateConPath)) return;
        File.WriteAllText(templateConPath, PatchSoldierSpawnTemplates(File.ReadAllLines(templateConPath), spawns));
    }
}
