using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using RefractorForge.Formats.Geometry;

namespace RefractorForge.Formats.Con;

/// <summary>
/// Writes the gameplay layer back to Refractor <c>.con</c> files. The three instance files
/// (ControlPoints / ObjectSpawns / SoldierSpawns) are regenerated from the edited model; capture
/// radii — which live on the control-point <em>templates</em> — are patched surgically into
/// ControlPointTemplates.con so every unrelated template property is preserved verbatim.
/// </summary>
public static class GameplayWriter
{
    private const string NL = "\r\n";   // Refractor .con files use CRLF
    private static string F(float v) => v.ToString("0.######", CultureInfo.InvariantCulture);
    private static string Pos(Vec3 v) => $"{F(v.X)}/{F(v.Y)}/{F(v.Z)}";

    public static string BuildControlPoints(IReadOnlyList<ControlPointDef> cps)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var c in cps)
            sb.Append("Object.create ").Append(c.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(c.Position)).Append(NL).Append(NL);
        return sb.ToString();
    }

    public static string BuildObjectSpawns(IReadOnlyList<VehicleSpawnDef> spawns)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var s in spawns)
            sb.Append("Object.create ").Append(s.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(s.Position)).Append(NL)
              .Append("Object.rotation ").Append(Pos(s.Rotation)).Append(NL)
              .Append("Object.setTeam ").Append(s.Team.ToString(CultureInfo.InvariantCulture)).Append(NL)
              .Append("Object.setOSId ").Append(s.OsId.ToString(CultureInfo.InvariantCulture)).Append(NL).Append(NL);
        return sb.ToString();
    }

    public static string BuildSoldierSpawns(IReadOnlyList<SoldierSpawnDef> spawns)
    {
        var sb = new StringBuilder();
        sb.Append("rem  Generated by RefractorForge").Append(NL).Append(NL);
        foreach (var s in spawns)
            sb.Append("Object.create ").Append(s.Name).Append(NL)
              .Append("Object.absolutePosition ").Append(Pos(s.Position)).Append(NL)
              .Append("Object.rotation ").Append(Pos(s.Rotation)).Append(NL).Append(NL);
        return sb.ToString();
    }

    /// <summary>Write the three instance files into <paramref name="dir"/>.</summary>
    public static void WriteInstanceFiles(string dir, GameplayObjects gp)
    {
        File.WriteAllText(Path.Combine(dir, "ControlPoints.con"), BuildControlPoints(gp.ControlPoints));
        File.WriteAllText(Path.Combine(dir, "ObjectSpawns.con"), BuildObjectSpawns(gp.VehicleSpawns));
        File.WriteAllText(Path.Combine(dir, "SoldierSpawns.con"), BuildSoldierSpawns(gp.SoldierSpawns));
    }

    /// <summary>Surgically rewrite the editable control-point template properties (radius, team, areaValue,
    /// conversionTime, controlPointName) for each template whose name matches an edited control point. Only
    /// EXISTING lines are rewritten; every other line is preserved exactly. Returns the patched text.</summary>
    public static string PatchControlPointRadii(IEnumerable<string> templateLines, IReadOnlyList<ControlPointDef> cps)
    {
        var byName = new Dictionary<string, ControlPointDef>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var c in cps) byName[c.Name] = c;   // last write wins

        var sb = new StringBuilder();
        ControlPointDef? cur = null;
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";

            if (key == "objecttemplate.create")
            {
                string? name = sp.Length >= 3 ? sp[2] : (sp.Length >= 2 ? sp[1] : null);   // "create ControlPoint <name>"
                cur = name is not null && byName.TryGetValue(name, out var c) ? c : null;
            }
            else if (cur is ControlPointDef cp)
            {
                string? repl = key switch
                {
                    "objecttemplate.radius" => "ObjectTemplate.radius " + cp.Radius.ToString("0.###", CultureInfo.InvariantCulture),
                    "objecttemplate.team" => "ObjectTemplate.team " + cp.Team.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.areavalue" => "ObjectTemplate.areaValue " + cp.AreaValue.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.conversiontime" => "ObjectTemplate.conversionTime " + cp.ConversionTime.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.controlpointname" when !string.IsNullOrEmpty(cp.ControlPointName) => "ObjectTemplate.controlPointName " + cp.ControlPointName,
                    // BF1942 control-point timing / behaviour fields (Battlecraft "Edit Control Point" dialog).
                    "objecttemplate.timetogetcontrol" => "ObjectTemplate.timeToGetControl " + cp.TimeToGetControl.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.timetolosecontrol" => "ObjectTemplate.timeToLoseControl " + cp.TimeToLoseControl.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.disableifenemyinsideradius" => "ObjectTemplate.disableIfEnemyInsideRadius " + cp.DisableIfEnemyInside.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.disablewhenlosingcontrol" => "ObjectTemplate.disableWhenLosingControl " + cp.DisableWhenLosing.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.losecontrolwhenenemyclose" => "ObjectTemplate.loseControlWhenEnemyClose " + cp.LoseControlWhenEnemyClose.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.losecontrolwhennotclose" => "ObjectTemplate.loseControlWhenNotClose " + cp.LoseControlWhenNotClose.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.unabletochangeteam" => "ObjectTemplate.unableToChangeTeam " + cp.UnableToChangeTeam.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.onlytakablebyteam" => "ObjectTemplate.onlyTakableByTeam " + cp.OnlyTakableByTeam.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.hascollisionphysics" => "ObjectTemplate.hasCollisionPhysics " + cp.HasCollisionPhysics.ToString(CultureInfo.InvariantCulture),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    sb.Append(line, 0, indent).Append(repl).Append(NL);
                    continue;
                }
            }
            sb.Append(line).Append(NL);
        }
        return sb.ToString();
    }

    public static void PatchControlPointRadiiFile(string templateConPath, IReadOnlyList<ControlPointDef> cps)
    {
        if (!File.Exists(templateConPath)) return;
        var patched = PatchControlPointRadii(File.ReadAllLines(templateConPath), cps);
        File.WriteAllText(templateConPath, patched);
    }

    /// <summary>Append <c>ObjectSpawner</c> templates for vehicle spawns that don't already have one (i.e.
    /// newly placed spawners), linking each to its chosen vehicle for both teams so it spawns in-game.
    /// Existing templates are preserved verbatim; spawns with no vehicle set or a known name are skipped.</summary>
    public static string AppendMissingSpawnerTemplates(IEnumerable<string> templateLines, IReadOnlyList<VehicleSpawnDef> spawns)
    {
        var have = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        var sb = new StringBuilder();
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var t = line.TrimStart();
            if (t.ToLowerInvariant().StartsWith("objecttemplate.create") && t.ToLowerInvariant().Contains("objectspawner"))
            {
                var sp = t.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
                if (sp.Length >= 3) have.Add(sp[2]);
            }
            sb.Append(line).Append(NL);
        }

        var added = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var s in spawns)
        {
            if (string.IsNullOrWhiteSpace(s.Vehicle) || have.Contains(s.Name) || !added.Add(s.Name)) continue;
            sb.Append(NL).Append("rem  Added by RefractorForge").Append(NL)
              .Append("ObjectTemplate.create ObjectSpawner ").Append(s.Name).Append(NL)
              .Append("ObjectTemplate.setObjectTemplate 1 ").Append(s.Vehicle).Append(NL)
              .Append("ObjectTemplate.setObjectTemplate 2 ").Append(s.Vehicle).Append(NL)
              .Append("ObjectTemplate.SpawnDelay 20").Append(NL)
              .Append("ObjectTemplate.SpawnDelayAtStart 0").Append(NL)
              .Append("ObjectTemplate.TimeToLive 120").Append(NL)
              .Append("ObjectTemplate.Distance 200").Append(NL);
        }
        return sb.ToString();
    }

    /// <summary>Surgically rewrite the editable soldier-spawn template fields (setGroup / setSpawnId /
    /// spawnAsParaTrooper) for each SpawnPoint template whose name matches an edited soldier spawn. Only EXISTING
    /// lines are rewritten; every other line is preserved verbatim (mirrors <see cref="PatchControlPointRadii"/>).</summary>
    public static string PatchSoldierSpawnTemplates(IEnumerable<string> templateLines, IReadOnlyList<SoldierSpawnDef> spawns)
    {
        var byName = new Dictionary<string, SoldierSpawnDef>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var s in spawns) byName[s.Name] = s;
        var sb = new StringBuilder();
        SoldierSpawnDef? cur = null;
        foreach (var raw in templateLines)
        {
            var line = raw.Replace("\r", "").Replace("\n", "");
            var trimmed = line.TrimStart();
            var sp = trimmed.Split(new[] { ' ', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
            var key = sp.Length > 0 ? sp[0].ToLowerInvariant() : "";
            if (key == "objecttemplate.create")
            {
                string? name = sp.Length >= 3 ? sp[2] : (sp.Length >= 2 ? sp[1] : null);   // "create SpawnPoint <name>"
                cur = name is not null && byName.TryGetValue(name, out var s) ? s : null;
            }
            else if (cur is SoldierSpawnDef ss)
            {
                string? repl = key switch
                {
                    "objecttemplate.setgroup" => "ObjectTemplate.setGroup " + ss.Group.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.setspawnid" => "ObjectTemplate.setSpawnId " + ss.SpawnId.ToString(CultureInfo.InvariantCulture),
                    "objecttemplate.spawnasparatrooper" => "ObjectTemplate.spawnAsParaTrooper " + ss.SpawnAsParaTrooper.ToString(CultureInfo.InvariantCulture),
                    _ => null,
                };
                if (repl is not null)
                {
                    int indent = line.Length - trimmed.Length;
                    sb.Append(line, 0, indent).Append(repl).Append(NL);
                    continue;
                }
            }
            sb.Append(line).Append(NL);
        }
        return sb.ToString();
    }

    public static void PatchSoldierSpawnTemplatesFile(string templateConPath, IReadOnlyList<SoldierSpawnDef> spawns)
    {
        if (!File.Exists(templateConPath)) return;
        File.WriteAllText(templateConPath, PatchSoldierSpawnTemplates(File.ReadAllLines(templateConPath), spawns));
    }
}
