namespace RefractorForge.Studio;

internal static class Program
{
    [STAThread]
    private static void Main()
    {
        // Source-generated by the WinForms SDK; applies the high-DPI mode + visual styles set in the csproj.
        ApplicationConfiguration.Initialize();
        Application.Run(new MainForm());
    }
}
